### ISSUE TITLE
Resolving referenced content only resolves the Sys property

### ISSUE THREAD

**Issue by sethreidnz** [contentful/contentful.net#105]
> Note: Using version 0.3.1-alpha since not sure I want to update to .net core 2.0 just yet

I have been banging my head against a wall and reading the docs trying to figure out if this is expected behavior. When I am using the .NET Core library I find that if I use the .Include() method it works in the sense that it resolves the referenced items. However it does not resolve the fields in the item except for the `Sys` field. Is this expected?

Say I have a content type and it is represented by these two classes (with a base class too):

``` csharp
  public class MenuItemBase : ContentfulBase
  {
    public string Title { get; set; }
  }

   public class MainMenuItem : MenuItemBase
  {
    public Asset DefaultIcon { get; set; }

    public Asset SecondaryIcon { get; set; }

    public IEnumerable<SubMenuItem> SubMenuItems { get; set; }
  }

  public class SubMenuItem : MenuItemBase
  {
    public string LinkUrl { get; set; }
  }
```

And I want to query all of the `MainMenuItem` content types like so (and include ALL of the content of the SubMenuItem like so:

``` csharp
    public async Task<IEnumerable<MainMenuItem>> GetAllMainMenuItems<MainMenuItem>(string contentTypeName)
    {
      var queryBuilder = new QueryBuilder<MainMenuItem>()
                         .ContentTypeIs(contentTypeName)
                         .Include(1); // This could be 2,3,4 or whatever doesn't seem to make any difference
      return (await _contentfulClient.GetEntriesAsync(queryBuilder)).ToList();
    }
````

When I inspect the result we have a the `SubMenuItem` array returned but the objects have all their properties null except for the `Sys` property.

This means I have to do a bunch of mapping and refactoring and do two API calls to get the info. Is this supposed to be happening? Am I missing something?

**Comment by Roblinde** [comment]
Hi Seth!

It's quite an old version you're using. You should be able to safely upgrade to v 0.7.6-beta if you're running contentful.aspnetcore or v 0.14.5-beta if you're running contentful.csharp. (I do recommend an upgrade to NetStandard 2.0 though)

If you upgrade hopefully you'll find that the deserialization is working as expected.

**Comment by sethreidnz** [comment]
I'm going to close this since it is fixed in the latest version. However one thing worth thinking about that I ran up against is the way that JSON.net handles metadata and duplicate references.

For example I had a content type that had a reference field that was the same content type. E.G. I had an Event content type, and it had a reference field of RelatedEvents of type Event. This caused issues because there were duplicate entries and I was able to find a work around for my case but it is potentially something worth thinking about. Setting the `MetadataPropertyHandling` to Ignore on the serialize removes the issue but probably has other implications that might not be ideal. Thanks for your help and glad I could contrib something too!

**Comment by Roblinde** [comment]
That's interesting, what kind of issues did you run into? In general I think looped referencing should already be handled by default. Or did you run into a scenario where this actually did not work?

**Comment by sethreidnz** [comment]
I get this sort of error:

```
System.ArgumentException occurred
  HResult=0x80070057
  Message=A different value already has the Id '22PqceEGraQsMOa0EkW6uc'.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Utilities.BidirectionalDictionary`2.Set(TFirst first, TSecond second)
   at Contentful.Core.Configuration.AssetJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Contentful.Core.ContentfulClient.<GetEntriesAsync>d__18`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Contentful.Core.ContentfulClient.<GetEntriesAsync>d__17`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```
I believe that it is because of how the deserialization and referencing is done in json.NET. Basically if you have an item appear in a reference field before it appears at the top level in a list of content entries, then it blows up like this.

Let me know if you need more details

**Comment by sethreidnz** [comment]
Actually that above error is slightly different, it is from having the same asset on two different items in a list. The ID appears twice, and it produced that error.

**Comment by Roblinde** [comment]
Thanks Seth, that's very helpful. I'll try and see if I can reproduce this locally.

**Comment by sethreidnz** [comment]
For more info what you need to do is:

1) Create a content type that has an asset field
2) Create two of them with the same Asset 
3) Do a query like:

```
var queryBuilder = new QueryBuilder<T>()
                         .ContentTypeIs(contentTypeName));
await _contentfulClient.GetEntriesAsync(queryBuilder));
```

**Comment by Roblinde** [comment]
I just created a small unit test locally and I can't seem to reproduce it. Are you running the latest version of the SDK?

I'll keep investigating.

**Comment by Roblinde** [comment]
I also ran it in an asp.net core application directly now.

Code like this:

```
public class Thingy
    {
        public Asset Field4 { get; set; }
    }

public async Task OnGet()
        {
            var res = await client.GetEntriesAsync(QueryBuilder<Thingy>.New.ContentTypeIs("testagain"));
            var test = res.First().Field4;
        }
```

The actual JSON returned looks like this (with some ids redacted):

```
{
  "sys": {
    "type": "Array"
  },
  "total": 2,
  "skip": 0,
  "limit": 100,
  "items": [
    {
      "sys": {
        "space": {
          "sys": {
            "type": "Link",
            "linkType": "Space",
            "id": "spaceid"
          }
        },
        "id": "entry1",
        "type": "Entry",
        "createdAt": "2017-02-10T12:34:15.614Z",
        "updatedAt": "2017-09-07T05:57:52.335Z",
        "revision": 2,
        "contentType": {
          "sys": {
            "type": "Link",
            "linkType": "ContentType",
            "id": "testagain"
          }
        },
        "locale": "en-US"
      },
      "fields": {
        "field1": "bdbd",
        "field2": {
          "lon": 15.5126953125,
          "lat": 49.56886849239747
        },
        "field4": {
          "sys": {
            "type": "Link",
            "linkType": "Asset",
            "id": "asset1"
          }
        },
        "image": {
          "sys": {
            "type": "Link",
            "linkType": "Asset",
            "id": "asset1"
          }
        }
      }
    },
    {
      "sys": {
        "space": {
          "sys": {
            "type": "Link",
            "linkType": "Space",
            "id": "spaceid"
          }
        },
        "id": "entry2",
        "type": "Entry",
        "createdAt": "2017-09-07T05:58:12.162Z",
        "updatedAt": "2017-09-07T05:58:12.162Z",
        "revision": 1,
        "contentType": {
          "sys": {
            "type": "Link",
            "linkType": "ContentType",
            "id": "testagain"
          }
        },
        "locale": "en-US"
      },
      "fields": {
        "field1": "bdbd22",
        "field2": {
          "lon": 15.5126953125,
          "lat": 49.56886849239747
        },
        "field4": {
          "sys": {
            "type": "Link",
            "linkType": "Asset",
            "id": "asset1"
          }
        },
        "image": {
          "sys": {
            "type": "Link",
            "linkType": "Asset",
            "id": "asset1"
          }
        }
      }
    }
  ],
  "includes": {
    "Asset": [
      {
        "sys": {
          "space": {
            "sys": {
              "type": "Link",
              "linkType": "Space",
              "id": "spaceid"
            }
          },
          "id": "asset1",
          "type": "Asset",
          "createdAt": "2017-02-10T12:34:00.053Z",
          "updatedAt": "2017-02-10T12:34:00.053Z",
          "revision": 1,
          "locale": "en-US"
        },
        "fields": {
          "title": "logo",
          "file": {
            "url": "//images.contentful.com//logo.png",
            "details": {
              "size": 13573,
              "image": {
                "width": 142,
                "height": 142
              }
            },
            "fileName": "logo.png",
            "contentType": "image/png"
          }
        }
      }
    ]
  }
}
```

As you can see the same asset is referenced from both entries multiple times.

Is there anything different in your setup that you can think of?
