### ISSUE TITLE
Error when getting Linked entry from "Document" type

### ISSUE THREAD

**Issue by ErikEJ** [contentful/contentful.net#272]
Please let me know if there is any additional information I can contribute.

Client version 6.0.17, .NET 6
```
Newtonsoft.Json.JsonSerializationException: Error setting value to 'Target' on 'Contentful.Core.Models.EntryStructureData'.
 ---> System.InvalidCastException: Unable to cast object of type 'Stepup.Domain.CMS.Articles.CMSArticleDTO' to type 'Contentful.Core.Models.IContent'.
   at lambda_method713(Closure , Object , Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Contentful.Core.Configuration.ContentJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at Contentful.Core.Configuration.ContentJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)

```

**Comment by Roblinde** [comment]
Hi @ErikEJ 
Could it be that you haven't given your class `CMSArticleDTO` the `IContent` interface? That interface is a marker that shows that you intend the content class to be part of a rich text structure. If you add that interface to your class (or classes if you have several that might be part of the rich text) I hope you'll get the expected result.

**Comment by ErikEJ** [comment]
Let me try that, oddly enough everything else works with the "Document" property in that class.

Where is this interface documented?

**Comment by ErikEJ** [comment]
It did not work, further debugging reveals that the issue occurs only if you have to "Entry links" in the same paragraph!

**Comment by Roblinde** [comment]
Hi @ErikEJ I don't seem to have any such problems with multiple entry links with the same paragraph. I'm assuming you have implemented a custom renderer for entries, could there be something in there that is causing issues?

**Comment by ErikEJ** [comment]
No custom renderer, simply having a Document property in my class.

I can upload a repro video...

**Comment by ErikEJ** [comment]
Or share the offending payload?

I have two Document properties in.my class, not sure if that makes any difference?

**Comment by Roblinde** [comment]
The payload would be perfect, then I can have a look.

**Comment by ErikEJ** [comment]
What is the simplest way to get the payload either the .net sdk?

**Comment by Roblinde** [comment]
The simplest is probably to mimic the query and go to https://cdn.contentful.com/spaces/{spacId}/entries?access_token={acctoken}&{restofQuery}

Be careful to redact anything you don't want to be public or send me an email with it instead.

**Comment by ErikEJ** [comment]
Unbale to get a repro after the first incident, and follow up issues turned out to be non-related.

**Comment by Roblinde** [comment]
Thank you for investigating @ErikEJ
